In [2]:
import pandas as pd
JA = pd.read_csv("Jamaican Creole.csv")
HA = pd.read_csv("hatian_creole_dictionary_v4.csv")

In [3]:
JA = JA[['Words','Definition','Country']]
JA.rename(columns={"Words": "creole_word", "Definition": "word", "Country":"creole name"}, inplace=True)
JA

                creole_word                             word      creole name
0                         a                        is, are    Jamaican Creole
1                      a bi                          being    Jamaican Creole
2                    a call                        calling    Jamaican Creole
3                     a cum                         coming    Jamaican Creole
4     a dat fi appen to yuh            You had that coming    Jamaican Creole
...                     ...                              ...              ...
1100         Weh yuh ah seh             How are you doing?    Jamaican Creole
1101       Weh yuh cum fram            Where are you from?    Jamaican Creole
1102            Weh yuh deh  Where are you?, where are you    Jamaican Creole
1103        Weh yuh deh pon            What are you up to?    Jamaican Creole
1104            Weh yuh seh                What did you say?  Jamaican Creole

[1105 rows x 3 columns]

In [4]:
HA

         word                                        creole_word creole name
0       a, an                                               youn     Haitian
1       aback                      pa sipriz (taken by surprise)     Haitian
2     abandon                                     abandone, kite     Haitian
3       abase  abese (to lower in rank-office-prestige), ~dim...     Haitian
4       abash     demoralize (to destroy the self-confidence of)     Haitian
...       ...                                                ...         ...
5820     tool                                              zouti     Haitian
5821   oyster                                        zuit (zwit)     Haitian
5822    goose                                                zwa     Haitian
5823     bird                                              zwazo     Haitian
5824      eye                                                zye     Haitian

[5825 rows x 3 columns]

In [7]:
to_merge = [JA,HA]

merged = pd.concat(to_merge)
merged.to_csv("Creole_merged_CSV.csv",index=False)
merged.to_json("Creole_merged_JSON.json",orient='records')